# Generated by rust2rpm 27
%bcond check 1
%global debug_package %{nil}

%global crate protobuf-json-mapping

Name:           rust-protobuf-json-mapping
Version:        3.7.2
Release:        1%{?dist}
Summary:        JSON mapping for Protocol Buffers messages

License:        MIT
URL:            https://crates.io/crates/protobuf-json-mapping
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
JSON mapping for Protocol Buffers messages.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE.txt
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Tue Oct 21 2025 Mat Booth <mat.booth@gmail.com> - 3.7.2-1
- Initial package
