# Generated by rust2rpm 26
%bcond_without check
%global debug_package %{nil}

%global crate librespot-playback

Name:           rust-librespot-playback
Version:        0.4.2
Release:        %autorelease
Summary:        Audio playback logic for librespot

License:        MIT
URL:            https://crates.io/crates/librespot-playback
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
The audio playback logic for librespot.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
# FIXME: no license files detected
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+alsa-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+alsa-devel %{_description}

This package contains library source intended for building other packages which
use the "alsa" feature of the "%{crate}" crate.

%files       -n %{name}+alsa-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+alsa-backend-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+alsa-backend-devel %{_description}

This package contains library source intended for building other packages which
use the "alsa-backend" feature of the "%{crate}" crate.

%files       -n %{name}+alsa-backend-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+cpal-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+cpal-devel %{_description}

This package contains library source intended for building other packages which
use the "cpal" feature of the "%{crate}" crate.

%files       -n %{name}+cpal-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+glib-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+glib-devel %{_description}

This package contains library source intended for building other packages which
use the "glib" feature of the "%{crate}" crate.

%files       -n %{name}+glib-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+gstreamer-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+gstreamer-devel %{_description}

This package contains library source intended for building other packages which
use the "gstreamer" feature of the "%{crate}" crate.

%files       -n %{name}+gstreamer-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+gstreamer-app-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+gstreamer-app-devel %{_description}

This package contains library source intended for building other packages which
use the "gstreamer-app" feature of the "%{crate}" crate.

%files       -n %{name}+gstreamer-app-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+gstreamer-audio-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+gstreamer-audio-devel %{_description}

This package contains library source intended for building other packages which
use the "gstreamer-audio" feature of the "%{crate}" crate.

%files       -n %{name}+gstreamer-audio-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+gstreamer-backend-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+gstreamer-backend-devel %{_description}

This package contains library source intended for building other packages which
use the "gstreamer-backend" feature of the "%{crate}" crate.

%files       -n %{name}+gstreamer-backend-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+jack-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+jack-devel %{_description}

This package contains library source intended for building other packages which
use the "jack" feature of the "%{crate}" crate.

%files       -n %{name}+jack-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+jackaudio-backend-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+jackaudio-backend-devel %{_description}

This package contains library source intended for building other packages which
use the "jackaudio-backend" feature of the "%{crate}" crate.

%files       -n %{name}+jackaudio-backend-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+libpulse-binding-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+libpulse-binding-devel %{_description}

This package contains library source intended for building other packages which
use the "libpulse-binding" feature of the "%{crate}" crate.

%files       -n %{name}+libpulse-binding-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+libpulse-simple-binding-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+libpulse-simple-binding-devel %{_description}

This package contains library source intended for building other packages which
use the "libpulse-simple-binding" feature of the "%{crate}" crate.

%files       -n %{name}+libpulse-simple-binding-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+portaudio-backend-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+portaudio-backend-devel %{_description}

This package contains library source intended for building other packages which
use the "portaudio-backend" feature of the "%{crate}" crate.

%files       -n %{name}+portaudio-backend-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+portaudio-rs-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+portaudio-rs-devel %{_description}

This package contains library source intended for building other packages which
use the "portaudio-rs" feature of the "%{crate}" crate.

%files       -n %{name}+portaudio-rs-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+pulseaudio-backend-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+pulseaudio-backend-devel %{_description}

This package contains library source intended for building other packages which
use the "pulseaudio-backend" feature of the "%{crate}" crate.

%files       -n %{name}+pulseaudio-backend-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rodio-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rodio-devel %{_description}

This package contains library source intended for building other packages which
use the "rodio" feature of the "%{crate}" crate.

%files       -n %{name}+rodio-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rodio-backend-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rodio-backend-devel %{_description}

This package contains library source intended for building other packages which
use the "rodio-backend" feature of the "%{crate}" crate.

%files       -n %{name}+rodio-backend-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rodiojack-backend-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rodiojack-backend-devel %{_description}

This package contains library source intended for building other packages which
use the "rodiojack-backend" feature of the "%{crate}" crate.

%files       -n %{name}+rodiojack-backend-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+sdl-backend-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+sdl-backend-devel %{_description}

This package contains library source intended for building other packages which
use the "sdl-backend" feature of the "%{crate}" crate.

%files       -n %{name}+sdl-backend-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+sdl2-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+sdl2-devel %{_description}

This package contains library source intended for building other packages which
use the "sdl2" feature of the "%{crate}" crate.

%files       -n %{name}+sdl2-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
