# Generated by rust2rpm 26
%bcond_with check
%global debug_package %{nil}

%global crate librespot-core

Name:           rust-librespot-core
Version:        0.4.2
Release:        %autorelease
Summary:        Core functionality provided by librespot

License:        MIT
URL:            https://crates.io/crates/librespot-core
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

Patch0: 0001-Update-aes-version.patch
Patch1: 0002-Update-hmac-sha1-pbkdf2-versions.patch

%global _description %{expand:
The core functionality provided by librespot.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
# FIXME: no license files detected
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
