# Generated by rust2rpm 26
%bcond_without check

%global crate spotifyd

Name:           rust-spotifyd
Version:        0.3.5
Release:        %autorelease
Summary:        Spotify daemon

License:        GPL-3.0-only
URL:            https://crates.io/crates/spotifyd
Source:         %{crates_source}
# Automatically generated patch to strip dependencies and normalize metadata
Patch:          spotifyd-fix-metadata-auto.diff

Patch: 0001-Update-alsa-version.patch

BuildRequires:  cargo-rpm-macros >= 24
BuildRequires:  systemd-rpm-macros

%global _description %{expand:
A Spotify daemon.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
# FIXME: paste output of %%cargo_license_summary here
License:        # FIXME
# LICENSE.dependencies contains a full license breakdown

%description -n %{crate} %{_description}

%post -n %{crate}
%systemd_post %{crate}.service

%preun -n %{crate}
%systemd_preun %{crate}.service

%postun -n %{crate}
%systemd_postun_with_restart %{crate}.service

%files       -n %{crate}
%license LICENSE
%license LICENSE.dependencies
%doc CHANGELOG.md
%doc CONTRIBUTING.md
%doc CONTRIBUTORS.md
%doc README.md
%{_bindir}/%{crate}
%{_unitdir}/%{crate}.service

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install

install -m664 -D -t %{buildroot}%{_unitdir} contrib/%{crate}.service

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
