# Generated by rust2rpm 26
%bcond_without check

%global crate spotifyd

Name:           rust-spotifyd
Version:        0.3.5
Release:        %autorelease
Summary:        Spotify daemon

License:        GPL-3.0-only
URL:            https://crates.io/crates/spotifyd
Source:         %{crates_source}
Source:         spotifyd.conf
# Automatically generated patch to strip dependencies and normalize metadata
Patch:          spotifyd-fix-metadata-auto.diff

Patch: 0001-Update-alsa-version.patch
Patch: 0002-Use-dns-sd-feature-of-librespot-for-avahi-compatibil.patch

BuildRequires:  cargo-rpm-macros >= 24
BuildRequires:  systemd-rpm-macros
BuildRequires:  pkgconfig(libdns_sd)

%global _description %{expand:
A Spotify daemon.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
License:        0BSD OR MIT OR Apache-2.0 AND Apache-2.0 AND Apache-2.0 OR BSL-1.0 AND Apache-2.0 OR MIT AND Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT AND BSD-2-Clause AND BSD-3-Clause AND GPL-3.0-only AND LGPL-3.0 OR MPL-2.0 AND MIT AND MIT OR Apache-2.0 OR Zlib AND MIT OR BSD-3-Clause AND Unlicense OR MIT
# LICENSE.dependencies contains a full license breakdown

%description -n %{crate} %{_description}

%post -n %{crate}
%systemd_user_post %{crate}.service

%preun -n %{crate}
%systemd_user_preun %{crate}.service

%postun -n %{crate}
%systemd_user_postun_with_restart %{crate}.service

%files       -n %{crate}
%license LICENSE
%license LICENSE.dependencies
%doc CHANGELOG.md
%doc CONTRIBUTING.md
%doc CONTRIBUTORS.md
%doc README.md
%{_bindir}/%{crate}
%{_userunitdir}/%{crate}.service
%config(noreplace) %{_sysconfdir}/%{crate}.conf

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install

install -m644 -D -t %{buildroot}%{_userunitdir} contrib/%{crate}.service
install -m644 -D -t %{buildroot}%{_sysconfdir} %{SOURCE1}

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
