# Generated by rust2rpm 27
%bcond check 1
%global debug_package %{nil}

%global crate symphonia-bundle-mp3

Name:           rust-symphonia-bundle-mp3
Version:        0.5.5
Release:        1%{?dist}
Summary:        Pure Rust MP1, MP2, and MP3 demuxer and decoder

License:        MPL-2.0
URL:            https://crates.io/crates/symphonia-bundle-mp3
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Pure Rust MP1, MP2, and MP3 demuxer and decoder (a part of project
Symphonia).}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
# FIXME: no license files detected
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+mp1-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+mp1-devel %{_description}

This package contains library source intended for building other packages which
use the "mp1" feature of the "%{crate}" crate.

%files       -n %{name}+mp1-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+mp2-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+mp2-devel %{_description}

This package contains library source intended for building other packages which
use the "mp2" feature of the "%{crate}" crate.

%files       -n %{name}+mp2-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+mp3-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+mp3-devel %{_description}

This package contains library source intended for building other packages which
use the "mp3" feature of the "%{crate}" crate.

%files       -n %{name}+mp3-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sat Oct 18 2025 Mat Booth <mat.booth@gmail.com> - 0.5.5-1
- Initial package
