# Generated by rust2rpm 27
%bcond check 1
%global debug_package %{nil}

%global crate symphonia

Name:           rust-symphonia
Version:        0.5.5
Release:        1%{?dist}
Summary:        Pure Rust media container and audio decoding library

License:        MPL-2.0
URL:            https://crates.io/crates/symphonia
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Pure Rust media container and audio decoding library.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
# FIXME: no license files detected
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+adpcm-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+adpcm-devel %{_description}

This package contains library source intended for building other packages which
use the "adpcm" feature of the "%{crate}" crate.

%files       -n %{name}+adpcm-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+aiff-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+aiff-devel %{_description}

This package contains library source intended for building other packages which
use the "aiff" feature of the "%{crate}" crate.

%files       -n %{name}+aiff-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+flac-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+flac-devel %{_description}

This package contains library source intended for building other packages which
use the "flac" feature of the "%{crate}" crate.

%files       -n %{name}+flac-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+mkv-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+mkv-devel %{_description}

This package contains library source intended for building other packages which
use the "mkv" feature of the "%{crate}" crate.

%files       -n %{name}+mkv-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+mp1-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+mp1-devel %{_description}

This package contains library source intended for building other packages which
use the "mp1" feature of the "%{crate}" crate.

%files       -n %{name}+mp1-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+mp2-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+mp2-devel %{_description}

This package contains library source intended for building other packages which
use the "mp2" feature of the "%{crate}" crate.

%files       -n %{name}+mp2-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+mp3-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+mp3-devel %{_description}

This package contains library source intended for building other packages which
use the "mp3" feature of the "%{crate}" crate.

%files       -n %{name}+mp3-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+mpa-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+mpa-devel %{_description}

This package contains library source intended for building other packages which
use the "mpa" feature of the "%{crate}" crate.

%files       -n %{name}+mpa-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+ogg-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+ogg-devel %{_description}

This package contains library source intended for building other packages which
use the "ogg" feature of the "%{crate}" crate.

%files       -n %{name}+ogg-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+opt-simd-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+opt-simd-devel %{_description}

This package contains library source intended for building other packages which
use the "opt-simd" feature of the "%{crate}" crate.

%files       -n %{name}+opt-simd-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+opt-simd-avx-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+opt-simd-avx-devel %{_description}

This package contains library source intended for building other packages which
use the "opt-simd-avx" feature of the "%{crate}" crate.

%files       -n %{name}+opt-simd-avx-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+opt-simd-neon-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+opt-simd-neon-devel %{_description}

This package contains library source intended for building other packages which
use the "opt-simd-neon" feature of the "%{crate}" crate.

%files       -n %{name}+opt-simd-neon-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+opt-simd-sse-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+opt-simd-sse-devel %{_description}

This package contains library source intended for building other packages which
use the "opt-simd-sse" feature of the "%{crate}" crate.

%files       -n %{name}+opt-simd-sse-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+pcm-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+pcm-devel %{_description}

This package contains library source intended for building other packages which
use the "pcm" feature of the "%{crate}" crate.

%files       -n %{name}+pcm-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+symphonia-bundle-flac-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+symphonia-bundle-flac-devel %{_description}

This package contains library source intended for building other packages which
use the "symphonia-bundle-flac" feature of the "%{crate}" crate.

%files       -n %{name}+symphonia-bundle-flac-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+symphonia-bundle-mp3-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+symphonia-bundle-mp3-devel %{_description}

This package contains library source intended for building other packages which
use the "symphonia-bundle-mp3" feature of the "%{crate}" crate.

%files       -n %{name}+symphonia-bundle-mp3-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+symphonia-codec-adpcm-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+symphonia-codec-adpcm-devel %{_description}

This package contains library source intended for building other packages which
use the "symphonia-codec-adpcm" feature of the "%{crate}" crate.

%files       -n %{name}+symphonia-codec-adpcm-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+symphonia-codec-pcm-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+symphonia-codec-pcm-devel %{_description}

This package contains library source intended for building other packages which
use the "symphonia-codec-pcm" feature of the "%{crate}" crate.

%files       -n %{name}+symphonia-codec-pcm-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+symphonia-codec-vorbis-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+symphonia-codec-vorbis-devel %{_description}

This package contains library source intended for building other packages which
use the "symphonia-codec-vorbis" feature of the "%{crate}" crate.

%files       -n %{name}+symphonia-codec-vorbis-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+symphonia-format-mkv-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+symphonia-format-mkv-devel %{_description}

This package contains library source intended for building other packages which
use the "symphonia-format-mkv" feature of the "%{crate}" crate.

%files       -n %{name}+symphonia-format-mkv-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+symphonia-format-ogg-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+symphonia-format-ogg-devel %{_description}

This package contains library source intended for building other packages which
use the "symphonia-format-ogg" feature of the "%{crate}" crate.

%files       -n %{name}+symphonia-format-ogg-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+symphonia-format-riff-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+symphonia-format-riff-devel %{_description}

This package contains library source intended for building other packages which
use the "symphonia-format-riff" feature of the "%{crate}" crate.

%files       -n %{name}+symphonia-format-riff-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+vorbis-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+vorbis-devel %{_description}

This package contains library source intended for building other packages which
use the "vorbis" feature of the "%{crate}" crate.

%files       -n %{name}+vorbis-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+wav-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+wav-devel %{_description}

This package contains library source intended for building other packages which
use the "wav" feature of the "%{crate}" crate.

%files       -n %{name}+wav-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sat Oct 18 2025 Mat Booth <mat.booth@gmail.com> - 0.5.5-1
- Initial package
