# Generated by rust2rpm 27
%bcond check 1
%global debug_package %{nil}

%global crate if-addrs

Name:           rust-if-addrs
Version:        0.12.0
Release:        1%{?dist}
Summary:        Return interface IP addresses on Posix and windows systems

License:        MIT OR BSD-3-Clause
URL:            https://crates.io/crates/if-addrs
Source:         %{crates_source}
# Automatically generated patch to strip dependencies and normalize metadata
Patch:          if-addrs-fix-metadata-auto.diff

BuildRequires:  cargo-rpm-macros >= 24
BuildRequires:  iproute

%global _description %{expand:
Return interface IP addresses on Posix and windows systems.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-BSD
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+link-local-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+link-local-devel %{_description}

This package contains library source intended for building other packages which
use the "link-local" feature of the "%{crate}" crate.

%files       -n %{name}+link-local-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sun Oct 19 2025 Mat Booth <mat.booth@gmail.com> - 0.12.0-1
- Update if-addrs to version 0.12
