# Generated by rust2rpm 27
%bcond check 1
%global debug_package %{nil}

%global crate aws-lc-sys

Name:           rust-aws-lc-sys
Version:        0.27.1
Release:        1%{?dist}
Summary:        AWS-LC is a general-purpose cryptographic library

License:        ISC AND (Apache-2.0 OR ISC) AND OpenSSL
URL:            https://crates.io/crates/aws-lc-sys
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
AWS-LC is a general-purpose cryptographic library maintained by the AWS
Cryptography team for AWS and their customers. It іs based on code from
the Google BoringSSL project and the OpenSSL project.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%license %{crate_instdir}/aws-lc/LICENSE
%license %{crate_instdir}/aws-lc/third_party/fiat/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+asan-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+asan-devel %{_description}

This package contains library source intended for building other packages which
use the "asan" feature of the "%{crate}" crate.

%files       -n %{name}+asan-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+bindgen-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+bindgen-devel %{_description}

This package contains library source intended for building other packages which
use the "bindgen" feature of the "%{crate}" crate.

%files       -n %{name}+bindgen-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+prebuilt-nasm-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+prebuilt-nasm-devel %{_description}

This package contains library source intended for building other packages which
use the "prebuilt-nasm" feature of the "%{crate}" crate.

%files       -n %{name}+prebuilt-nasm-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+ssl-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+ssl-devel %{_description}

This package contains library source intended for building other packages which
use the "ssl" feature of the "%{crate}" crate.

%files       -n %{name}+ssl-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sun Oct 19 2025 Mat Booth <mat.booth@gmail.com> - 0.27.1-1
- Initial package
