# Generated by rust2rpm 27
%bcond check 1
%global debug_package %{nil}

%global crate symphonia-format-riff

Name:           rust-symphonia-format-riff
Version:        0.5.5
Release:        1%{?dist}
Summary:        Pure Rust RIFF demuxer (a part of project Symphonia)

License:        MPL-2.0
URL:            https://crates.io/crates/symphonia-format-riff
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Pure Rust RIFF demuxer (a part of project Symphonia).}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
# FIXME: no license files detected
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+aiff-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+aiff-devel %{_description}

This package contains library source intended for building other packages which
use the "aiff" feature of the "%{crate}" crate.

%files       -n %{name}+aiff-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+wav-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+wav-devel %{_description}

This package contains library source intended for building other packages which
use the "wav" feature of the "%{crate}" crate.

%files       -n %{name}+wav-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sat Oct 18 2025 Mat Booth <mat.booth@gmail.com> - 0.5.5-1
- Initial package
