# Generated by rust2rpm 27
%bcond check 1
%global debug_package %{nil}

%global crate spinning_top

Name:           rust-spinning_top
Version:        0.3.0
Release:        1%{?dist}
Summary:        Simple spinlock crate based on the abstractions provided by lock_api

# Upstream license specification: MIT/Apache-2.0
License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/spinning_top
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
A simple spinlock crate based on the abstractions provided by
`lock_api`.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/Changelog.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+arc_lock-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+arc_lock-devel %{_description}

This package contains library source intended for building other packages which
use the "arc_lock" feature of the "%{crate}" crate.

%files       -n %{name}+arc_lock-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+owning_ref-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+owning_ref-devel %{_description}

This package contains library source intended for building other packages which
use the "owning_ref" feature of the "%{crate}" crate.

%files       -n %{name}+owning_ref-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Thu Oct 16 2025 Mat Booth <mat.booth@gmail.com> - 0.3.0-1
- Initial package
