[features]
hide = [ "fips" ]

[tests]
run = "none"
comments = [ "Tests disabled due to missing dependencies" ]

[[package.extra-patches]]
number = 10
file = "0001-bump-version-of-untrusted-dependency.patch"
comments = [ "Use version of this dependency that is shipped by Fedora" ]

[[package.extra-patches]]
number = 11
file = "0002-remove-dep-on-fips-variant.patch"
comments = [ "Remove dependency on the FIPS variant of the implementation" ]
