# Generated by rust2rpm 27
%bcond check 1
%global debug_package %{nil}

%global crate librespot-discovery

Name:           rust-librespot-discovery
Version:        0.6.0
Release:        1%{?dist}
Summary:        Discovery logic for librespot

License:        MIT
URL:            https://crates.io/crates/librespot-discovery
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
The discovery logic for librespot.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
# FIXME: no license files detected
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+dns-sd-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+dns-sd-devel %{_description}

This package contains library source intended for building other packages which
use the "dns-sd" feature of the "%{crate}" crate.

%files       -n %{name}+dns-sd-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+libmdns-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+libmdns-devel %{_description}

This package contains library source intended for building other packages which
use the "libmdns" feature of the "%{crate}" crate.

%files       -n %{name}+libmdns-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serde-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde-devel %{_description}

This package contains library source intended for building other packages which
use the "serde" feature of the "%{crate}" crate.

%files       -n %{name}+serde-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+with-avahi-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+with-avahi-devel %{_description}

This package contains library source intended for building other packages which
use the "with-avahi" feature of the "%{crate}" crate.

%files       -n %{name}+with-avahi-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+with-dns-sd-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+with-dns-sd-devel %{_description}

This package contains library source intended for building other packages which
use the "with-dns-sd" feature of the "%{crate}" crate.

%files       -n %{name}+with-dns-sd-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+with-libmdns-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+with-libmdns-devel %{_description}

This package contains library source intended for building other packages which
use the "with-libmdns" feature of the "%{crate}" crate.

%files       -n %{name}+with-libmdns-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+zbus-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+zbus-devel %{_description}

This package contains library source intended for building other packages which
use the "zbus" feature of the "%{crate}" crate.

%files       -n %{name}+zbus-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sun Oct 19 2025 Mat Booth <mat.booth@gmail.com> - 0.6.0-1
- Initial package
