# Generated by rust2rpm 27
# * Tests don't work in headless environment
%bcond check 0
%global debug_package %{nil}

%global crate dbus-tokio

Name:           rust-dbus-tokio
Version:        0.7.6
Release:        1%{?dist}
Summary:        Makes it possible to use Tokio with D-Bus

# Upstream license specification: Apache-2.0/MIT
License:        Apache-2.0 OR MIT
URL:            https://crates.io/crates/dbus-tokio
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Makes it possible to use Tokio with D-Bus, which is a bus commonly used
on Linux for inter-process communication.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+dbus-crossroads-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+dbus-crossroads-devel %{_description}

This package contains library source intended for building other packages which
use the "dbus-crossroads" feature of the "%{crate}" crate.

%files       -n %{name}+dbus-crossroads-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Mon Oct 20 2025 Mat Booth <mat.booth@gmail.com> - 0.7.6-1
- Initial package
