# Generated by rust2rpm 27
%bcond check 1
%global debug_package %{nil}

%global crate librespot-playback

Name:           rust-librespot-playback
Version:        0.6.0
Release:        1%{?dist}
Summary:        Audio playback logic for librespot

License:        MIT
URL:            https://crates.io/crates/librespot-playback
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
The audio playback logic for librespot.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
# FIXME: no license files detected
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+alsa-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+alsa-devel %{_description}

This package contains library source intended for building other packages which
use the "alsa" feature of the "%{crate}" crate.

%files       -n %{name}+alsa-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+alsa-backend-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+alsa-backend-devel %{_description}

This package contains library source intended for building other packages which
use the "alsa-backend" feature of the "%{crate}" crate.

%files       -n %{name}+alsa-backend-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+glib-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+glib-devel %{_description}

This package contains library source intended for building other packages which
use the "glib" feature of the "%{crate}" crate.

%files       -n %{name}+glib-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+gstreamer-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+gstreamer-devel %{_description}

This package contains library source intended for building other packages which
use the "gstreamer" feature of the "%{crate}" crate.

%files       -n %{name}+gstreamer-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+gstreamer-app-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+gstreamer-app-devel %{_description}

This package contains library source intended for building other packages which
use the "gstreamer-app" feature of the "%{crate}" crate.

%files       -n %{name}+gstreamer-app-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+gstreamer-audio-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+gstreamer-audio-devel %{_description}

This package contains library source intended for building other packages which
use the "gstreamer-audio" feature of the "%{crate}" crate.

%files       -n %{name}+gstreamer-audio-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+gstreamer-backend-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+gstreamer-backend-devel %{_description}

This package contains library source intended for building other packages which
use the "gstreamer-backend" feature of the "%{crate}" crate.

%files       -n %{name}+gstreamer-backend-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+libpulse-binding-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+libpulse-binding-devel %{_description}

This package contains library source intended for building other packages which
use the "libpulse-binding" feature of the "%{crate}" crate.

%files       -n %{name}+libpulse-binding-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+libpulse-simple-binding-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+libpulse-simple-binding-devel %{_description}

This package contains library source intended for building other packages which
use the "libpulse-simple-binding" feature of the "%{crate}" crate.

%files       -n %{name}+libpulse-simple-binding-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+pulseaudio-backend-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+pulseaudio-backend-devel %{_description}

This package contains library source intended for building other packages which
use the "pulseaudio-backend" feature of the "%{crate}" crate.

%files       -n %{name}+pulseaudio-backend-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sun Oct 19 2025 Mat Booth <mat.booth@gmail.com> - 0.6.0-1
- Initial package
