# Generated by rust2rpm 27
%bcond check 1
%global debug_package %{nil}

%global crate librespot-playback

Name:           rust-librespot-playback
Version:        0.7.1
Release:        1%{?dist}
Summary:        Audio playback logic for librespot

License:        MIT
URL:            https://crates.io/crates/librespot-playback
Source:         %{crates_source}
# * Switch to using alsa backend by default
Patch10:        0001-switch-to-alsa-backend-by-default.patch

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
The audio playback logic for librespot.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
# FIXME: no license files detected
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+alsa-backend-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+alsa-backend-devel %{_description}

This package contains library source intended for building other packages which
use the "alsa-backend" feature of the "%{crate}" crate.

%files       -n %{name}+alsa-backend-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+native-tls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+native-tls-devel %{_description}

This package contains library source intended for building other packages which
use the "native-tls" feature of the "%{crate}" crate.

%files       -n %{name}+native-tls-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+pulseaudio-backend-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+pulseaudio-backend-devel %{_description}

This package contains library source intended for building other packages which
use the "pulseaudio-backend" feature of the "%{crate}" crate.

%files       -n %{name}+pulseaudio-backend-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rustls-tls-native-roots-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rustls-tls-native-roots-devel %{_description}

This package contains library source intended for building other packages which
use the "rustls-tls-native-roots" feature of the "%{crate}" crate.

%files       -n %{name}+rustls-tls-native-roots-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rustls-tls-webpki-roots-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rustls-tls-webpki-roots-devel %{_description}

This package contains library source intended for building other packages which
use the "rustls-tls-webpki-roots" feature of the "%{crate}" crate.

%files       -n %{name}+rustls-tls-webpki-roots-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Tue Oct 21 2025 Mat Booth <mat.booth@gmail.com> - 0.7.1-1
- Update to latest released version

* Sun Oct 19 2025 Mat Booth <mat.booth@gmail.com> - 0.6.0-1
- Initial package
