[features]
hide = ["jackaudio-backend", "sdl-backend", "rodio-backend", "rodiojack-backend", "portaudio-backend", "gstreamer-backend", "passthrough-decoder" ]

[package]
cargo-toml-patch-comments = [
	"Switch to ALSA backend by default"
]

