# Generated by rust2rpm 27
%bcond check 1
%global debug_package %{nil}

%global crate no-std-compat

Name:           rust-no-std-compat
Version:        0.4.1
Release:        2%{?dist}
Summary:        Compatibility layer that will make porting your crate to no_std easy

License:        MIT
URL:            https://crates.io/crates/no-std-compat
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
A `#![no_std]` compatibility layer that will make porting your crate to
no_std *easy*.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+alloc-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+alloc-devel %{_description}

This package contains library source intended for building other packages which
use the "alloc" feature of the "%{crate}" crate.

%files       -n %{name}+alloc-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+compat_macros-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+compat_macros-devel %{_description}

This package contains library source intended for building other packages which
use the "compat_macros" feature of the "%{crate}" crate.

%files       -n %{name}+compat_macros-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages which
use the "std" feature of the "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+unstable-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+unstable-devel %{_description}

This package contains library source intended for building other packages which
use the "unstable" feature of the "%{crate}" crate.

%files       -n %{name}+unstable-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Fri Oct 17 2025 Mat Booth <mat.booth@gmail.com> - 0.4.1-2
- Drop unneeded subpackages

* Thu Oct 16 2025 Mat Booth <mat.booth@gmail.com> - 0.4.1-1
- Initial package
