# Generated by rust2rpm 27
# * Tests disabled due to missing dependencies
%bcond check 0
%global debug_package %{nil}

%global crate governor

Name:           rust-governor
Version:        0.6.3
Release:        2%{?dist}
Summary:        Rate-limiting implementation in Rust

License:        MIT
URL:            https://crates.io/crates/governor
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
A rate-limiting implementation in Rust.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
# FIXME: no license files detected
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+dashmap-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+dashmap-devel %{_description}

This package contains library source intended for building other packages which
use the "dashmap" feature of the "%{crate}" crate.

%files       -n %{name}+dashmap-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+futures-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+futures-devel %{_description}

This package contains library source intended for building other packages which
use the "futures" feature of the "%{crate}" crate.

%files       -n %{name}+futures-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+futures-timer-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+futures-timer-devel %{_description}

This package contains library source intended for building other packages which
use the "futures-timer" feature of the "%{crate}" crate.

%files       -n %{name}+futures-timer-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+jitter-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+jitter-devel %{_description}

This package contains library source intended for building other packages which
use the "jitter" feature of the "%{crate}" crate.

%files       -n %{name}+jitter-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+quanta-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+quanta-devel %{_description}

This package contains library source intended for building other packages which
use the "quanta" feature of the "%{crate}" crate.

%files       -n %{name}+quanta-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rand-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rand-devel %{_description}

This package contains library source intended for building other packages which
use the "rand" feature of the "%{crate}" crate.

%files       -n %{name}+rand-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages which
use the "std" feature of the "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
# Fix erroneous execute bits
chmod -x src/state/direct/streams.rs src/state/keyed/dashmap.rs src/lib.rs
chmod -x tests/future.rs tests/keyed_dashmap.rs tests/memory_leaks.rs tests/sinks.rs tests/streams.rs
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Fri Oct 17 2025 Mat Booth <mat.booth@gmail.com> - 0.6.3-2
- Drop unneeded no_std subpackage

* Thu Oct 16 2025 Mat Booth <mat.booth@gmail.com> - 0.6.3-1
- Initial package
