# Generated by rust2rpm 27
%bcond check 1
%global debug_package %{nil}

%global crate symphonia-core

Name:           rust-symphonia-core
Version:        0.5.5
Release:        1%{?dist}
Summary:        Project Symphonia shared structs, traits, and features

License:        MPL-2.0
URL:            https://crates.io/crates/symphonia-core
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Project Symphonia shared structs, traits, and features.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
# FIXME: no license files detected
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+opt-simd-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+opt-simd-devel %{_description}

This package contains library source intended for building other packages which
use the "opt-simd" feature of the "%{crate}" crate.

%files       -n %{name}+opt-simd-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+opt-simd-avx-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+opt-simd-avx-devel %{_description}

This package contains library source intended for building other packages which
use the "opt-simd-avx" feature of the "%{crate}" crate.

%files       -n %{name}+opt-simd-avx-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+opt-simd-neon-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+opt-simd-neon-devel %{_description}

This package contains library source intended for building other packages which
use the "opt-simd-neon" feature of the "%{crate}" crate.

%files       -n %{name}+opt-simd-neon-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+opt-simd-sse-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+opt-simd-sse-devel %{_description}

This package contains library source intended for building other packages which
use the "opt-simd-sse" feature of the "%{crate}" crate.

%files       -n %{name}+opt-simd-sse-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rustfft-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rustfft-devel %{_description}

This package contains library source intended for building other packages which
use the "rustfft" feature of the "%{crate}" crate.

%files       -n %{name}+rustfft-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sat Oct 18 2025 Mat Booth <mat.booth@gmail.com> - 0.5.5-1
- Initial package
