# Generated by rust2rpm 27
%bcond check 1
%global debug_package %{nil}

%global crate librespot-connect

Name:           rust-librespot-connect
Version:        0.6.0
Release:        1%{?dist}
Summary:        Discovery and Spotify Connect logic for librespot

License:        MIT
URL:            https://crates.io/crates/librespot-connect
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
The discovery and Spotify Connect logic for librespot.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
# FIXME: no license files detected
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sun Oct 19 2025 Mat Booth <mat.booth@gmail.com> - 0.6.0-1
- Initial package
