# Generated by rust2rpm 27
%bcond check 1
%global debug_package %{nil}

%global crate oauth2

Name:           rust-oauth2
Version:        4.4.2
Release:        1%{?dist}
Summary:        Extensible, strongly-typed implementation of OAuth2

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/oauth2
Source:         %{crates_source}
# Automatically generated patch to strip dependencies and normalize metadata
Patch:          oauth2-fix-metadata-auto.diff
# Manually created patch for downstream crate metadata changes
Patch:          oauth2-fix-metadata.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
An extensible, strongly-typed implementation of OAuth2.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+curl-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+curl-devel %{_description}

This package contains library source intended for building other packages which
use the "curl" feature of the "%{crate}" crate.

%files       -n %{name}+curl-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+native-tls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+native-tls-devel %{_description}

This package contains library source intended for building other packages which
use the "native-tls" feature of the "%{crate}" crate.

%files       -n %{name}+native-tls-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+pkce-plain-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+pkce-plain-devel %{_description}

This package contains library source intended for building other packages which
use the "pkce-plain" feature of the "%{crate}" crate.

%files       -n %{name}+pkce-plain-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+reqwest-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+reqwest-devel %{_description}

This package contains library source intended for building other packages which
use the "reqwest" feature of the "%{crate}" crate.

%files       -n %{name}+reqwest-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rustls-tls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rustls-tls-devel %{_description}

This package contains library source intended for building other packages which
use the "rustls-tls" feature of the "%{crate}" crate.

%files       -n %{name}+rustls-tls-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+ureq-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+ureq-devel %{_description}

This package contains library source intended for building other packages which
use the "ureq" feature of the "%{crate}" crate.

%files       -n %{name}+ureq-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sat Oct 18 2025 Mat Booth <mat.booth@gmail.com> - 4.4.2-1
- Initial package
