# Generated by rust2rpm 27
%bcond check 1
%global debug_package %{nil}

%global crate librespot-core

Name:           rust-librespot-core
Version:        0.6.0
Release:        2%{?dist}
Summary:        Core functionality provided by librespot

License:        MIT
URL:            https://crates.io/crates/librespot-core
Source:         %{crates_source}
# * Upgrade sysinfo to a version that is available in Fedora
Patch10:        0001-fix-sysinfo-dependency.patch
# * Backport change from upstream for newer tungstenite version
Patch11:        0002-fix-tungstenite-dependency.patch
# * Downgrade vergen to 8 because that's what Fedora has
Patch12:        0003-fix-vergen-dependency.patch

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
The core functionality provided by librespot.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
# FIXME: no license files detected
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sat Oct 18 2025 Mat Booth <mat.booth@gmail.com> - 0.6.0-2
- Patch dependencies on vergen, sysinfo and tungstenite

* Thu Oct 16 2025 Mat Booth <mat.booth@gmail.com> - 0.6.0-1
- Initial package
