# Generated by rust2rpm 27
%bcond check 1
%global debug_package %{nil}

%global crate libmdns

Name:           rust-libmdns
Version:        0.9.1
Release:        2%{?dist}
Summary:        MDNS Responder library for building discoverable LAN services in Rust

License:        MIT
URL:            https://crates.io/crates/libmdns
Source:         %{crates_source}
# * Relax version requirement on hostname dependency
Patch10:        0001-relax-hostname-version.patch
# * Relax version requirement on multimap dependency
Patch11:        0002-relax-multimap-version.patch

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
MDNS Responder library for building discoverable LAN services in Rust.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sun Oct 19 2025 Mat Booth <mat.booth@gmail.com> - 0.9.1-2
- Relax version requirement for dependencies

* Sun Oct 19 2025 Mat Booth <mat.booth@gmail.com> - 0.9.1-1
- Update libmdns to version 0.9.1
