# Generated by rust2rpm 26
%bcond_without check
%global debug_package %{nil}

%global crate libmdns

Name:           rust-libmdns
Version:        0.7.5
Release:        %autorelease
Summary:        MDNS Responder library for building discoverable LAN services in Rust

License:        MIT
URL:            https://crates.io/crates/libmdns
Source:         %{crates_source}
# Automatically generated patch to strip dependencies and normalize metadata
Patch:          libmdns-fix-metadata-auto.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
MDNS Responder library for building discoverable LAN services in Rust.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
