# Generated by rust2rpm 27
%bcond check 1
%global debug_package %{nil}

%global crate hyper-proxy2

Name:           rust-hyper-proxy2
Version:        0.1.0
Release:        3%{?dist}
Summary:        Proxy connector for Hyper-based applications

License:        MIT
URL:            https://crates.io/crates/hyper-proxy2
Source:         %{crates_source}
# * Downgrade to hyper-rustls 0.25 due to compile errors with the latest version
#   that Fedora has
Patch10:        0001-fix-hyper-rustls-dependency.patch

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
A proxy connector for Hyper-based applications.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-MIT.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+hyper-rustls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+hyper-rustls-devel %{_description}

This package contains library source intended for building other packages which
use the "hyper-rustls" feature of the "%{crate}" crate.

%files       -n %{name}+hyper-rustls-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+hyper-tls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+hyper-tls-devel %{_description}

This package contains library source intended for building other packages which
use the "hyper-tls" feature of the "%{crate}" crate.

%files       -n %{name}+hyper-tls-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+native-tls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+native-tls-devel %{_description}

This package contains library source intended for building other packages which
use the "native-tls" feature of the "%{crate}" crate.

%files       -n %{name}+native-tls-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+openssl-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+openssl-devel %{_description}

This package contains library source intended for building other packages which
use the "openssl" feature of the "%{crate}" crate.

%files       -n %{name}+openssl-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+openssl-tls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+openssl-tls-devel %{_description}

This package contains library source intended for building other packages which
use the "openssl-tls" feature of the "%{crate}" crate.

%files       -n %{name}+openssl-tls-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rustls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rustls-devel %{_description}

This package contains library source intended for building other packages which
use the "rustls" feature of the "%{crate}" crate.

%files       -n %{name}+rustls-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rustls-base-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rustls-base-devel %{_description}

This package contains library source intended for building other packages which
use the "rustls-base" feature of the "%{crate}" crate.

%files       -n %{name}+rustls-base-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rustls-native-certs-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rustls-native-certs-devel %{_description}

This package contains library source intended for building other packages which
use the "rustls-native-certs" feature of the "%{crate}" crate.

%files       -n %{name}+rustls-native-certs-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rustls-webpki-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rustls-webpki-devel %{_description}

This package contains library source intended for building other packages which
use the "rustls-webpki" feature of the "%{crate}" crate.

%files       -n %{name}+rustls-webpki-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tls-devel %{_description}

This package contains library source intended for building other packages which
use the "tls" feature of the "%{crate}" crate.

%files       -n %{name}+tls-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tokio-native-tls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tokio-native-tls-devel %{_description}

This package contains library source intended for building other packages which
use the "tokio-native-tls" feature of the "%{crate}" crate.

%files       -n %{name}+tokio-native-tls-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tokio-openssl-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tokio-openssl-devel %{_description}

This package contains library source intended for building other packages which
use the "tokio-openssl" feature of the "%{crate}" crate.

%files       -n %{name}+tokio-openssl-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tokio-rustls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tokio-rustls-devel %{_description}

This package contains library source intended for building other packages which
use the "tokio-rustls" feature of the "%{crate}" crate.

%files       -n %{name}+tokio-rustls-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+webpki-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+webpki-devel %{_description}

This package contains library source intended for building other packages which
use the "webpki" feature of the "%{crate}" crate.

%files       -n %{name}+webpki-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+webpki-roots-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+webpki-roots-devel %{_description}

This package contains library source intended for building other packages which
use the "webpki-roots" feature of the "%{crate}" crate.

%files       -n %{name}+webpki-roots-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sat Oct 18 2025 Mat Booth <mat.booth@gmail.com> - 0.1.0-3
- Downgrade hyper-rustls dep in rust-hyper-proxy2

* Fri Oct 17 2025 Mat Booth <mat.booth@gmail.com> - 0.1.0-2
- Patch dependency on hyper-rustls

* Fri Oct 17 2025 Mat Booth <mat.booth@gmail.com> - 0.1.0-1
- Initial package
