# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate libpulse-simple-sys

Name:           rust-libpulse-simple-sys
Version:        1.22.0
Release:        1%{?dist}
Summary:        FFI bindings for the PulseAudio libpulse-simple system library

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/libpulse-simple-sys
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
FFI bindings for the PulseAudio libpulse-simple system library.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+pa_v12-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+pa_v12-devel %{_description}

This package contains library source intended for building other packages which
use the "pa_v12" feature of the "%{crate}" crate.

%files       -n %{name}+pa_v12-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+pa_v13-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+pa_v13-devel %{_description}

This package contains library source intended for building other packages which
use the "pa_v13" feature of the "%{crate}" crate.

%files       -n %{name}+pa_v13-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+pa_v14-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+pa_v14-devel %{_description}

This package contains library source intended for building other packages which
use the "pa_v14" feature of the "%{crate}" crate.

%files       -n %{name}+pa_v14-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+pa_v15-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+pa_v15-devel %{_description}

This package contains library source intended for building other packages which
use the "pa_v15" feature of the "%{crate}" crate.

%files       -n %{name}+pa_v15-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+pa_v6-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+pa_v6-devel %{_description}

This package contains library source intended for building other packages which
use the "pa_v6" feature of the "%{crate}" crate.

%files       -n %{name}+pa_v6-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+pa_v8-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+pa_v8-devel %{_description}

This package contains library source intended for building other packages which
use the "pa_v8" feature of the "%{crate}" crate.

%files       -n %{name}+pa_v8-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires
echo 'pkgconfig(libpulse) >= 5.0'

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Wed Sep 30 2026 Mat Booth <mat.booth@gmail.com> - 1.22.0-1
- Initial libpulse-simple-sys package

